language: scala

scala:
 - 0.22.0-RC1
 - 0.21.0-RC1
 - 0.20.0-RC1

jdk:
  - openjdk8
  - openjdk11

before_cache:
  - find $HOME/.sbt -name '*.lock' -delete
  - find $HOME/.ivy2 -name 'ivydata-*.properties' -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION run

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.coursier/
